[tool.poetry]
name = "nerdtube"
version = "0.1.0"
description = ""
authors = ["NerdBow <108768934+NerdBow@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
